sudo: required 
services:
    - docker 
before_install:
    - docker build -t msanogo/react-test -f ./client/Dockerfile.dev  ./client
scripts: 
    - docker run -e CI=true msanogo/react-test yarn run test 
after_success:
    - docker build -t msanogo/multi-client ./client
    - docker build -t msanogo/multi-nginx ./nginx
    - docker build -t msanogo/multi-server ./server
    - docker build -t msanogo/multi-worker ./worker 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push msanogo/multi-client
    - docker push msanogo/multi-nginx
    - docker push msanogo/multi-server
    - docker push msanogo/multi-worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: ca-central-1
    app: multi-docker
    env: MultiDocker-env
    backet_name: elasticbeanstalk-ca-central-1-082594015364
    bucket_path: multi_docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY